version: "3.7"
services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # This volume maps the container's volume as an anonymous volume, preventing changes to the host's node_modules directory from being reflected in the container.
      - ./frontend:/app # This volume maps the host's ./frontend directory to the container's /app directory, allowing changes on the host to be reflected in the container.
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - ./frontend/.env.development
  api:
    restart: always
    build: ./api
    ports:
      - "5050:5050"
    volumes:
      - /app/.venv
      - ./api:/app
    env_file:
      - ./api/.env.development
